version: '3.7'
services:
  mongo:
    image : mongo:4.4.9
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/memoria/mongo/db:/data/db  #Change if needed
    ports:
      - "27017:27017"
    restart: always

  memoria:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mongo
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '~/memoria:/var/lib/memoria' #Change if needed
    expose:
      - "12480"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - memoria
    ports:
      - "12480:12480"
    restart: always
